// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.CronExpressionParser
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("expression")]
        public string Expression { get; set; }

        [JsonProperty("isValid")]
        public bool IsValid { get; set; }

        [JsonProperty("format")]
        public string Format { get; set; }

        [JsonProperty("fields")]
        public Fields Fields { get; set; }

        [JsonProperty("description")]
        public string Description { get; set; }

        [JsonProperty("frequency")]
        public Frequency Frequency { get; set; }
    }

    public partial class Fields
    {
        [JsonProperty("second")]
        public DayOfMonth Second { get; set; }

        [JsonProperty("minute")]
        public DayOfMonth Minute { get; set; }

        [JsonProperty("hour")]
        public DayOfMonth Hour { get; set; }

        [JsonProperty("dayOfMonth")]
        public DayOfMonth DayOfMonth { get; set; }

        [JsonProperty("month")]
        public DayOfMonth Month { get; set; }

        [JsonProperty("dayOfWeek")]
        public DayOfMonth DayOfWeek { get; set; }
    }

    public partial class DayOfMonth
    {
        [JsonProperty("expression")]
        public string Expression { get; set; }

        [JsonProperty("description")]
        public string Description { get; set; }

        [JsonProperty("values")]
        public long[] Values { get; set; }
    }

    public partial class Frequency
    {
        [JsonProperty("type")]
        public string Type { get; set; }

        [JsonProperty("interval")]
        public string Interval { get; set; }
    }
}
